# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('fathername', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
