# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='amount',
        ),
        migrations.AddField(
            model_name='certificate',
            name='cer_amount',
            field=models.IntegerField(default=0),
        ),
    ]
