# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0002_auto_20160714_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='text',
            new_name='certificate_text',
        ),
    ]
