# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0004_auto_20160718_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiceapp.Certificate')),
            ],
        ),
    ]
