# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0005_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='fathername',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='group',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='surname',
        ),
    ]
