# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0007_auto_20160719_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 17, 17, 12, 928293, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=datetime.datetime(2016, 7, 19, 17, 17, 58, 432016, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
