# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0009_auto_20160819_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysiteprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RemoveField(
            model_name='mysiteprofile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='mysiteprofile',
            name='lucky_number',
        ),
        migrations.RemoveField(
            model_name='mysiteprofile',
            name='status',
        ),
        migrations.AlterField(
            model_name='mysiteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
