# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0011_mysiteprofile_father_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysiteprofile',
            old_name='father_name',
            new_name='Отчество',
        ),
    ]
