# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0013_mysiteprofile_группа'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysiteprofile',
            name='Группа',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mysiteprofile',
            name='Отчество',
            field=models.CharField(max_length=20),
        ),
    ]
