# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0015_auto_20160819_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysiteprofile',
            old_name='group',
            new_name='Группа',
        ),
    ]
