# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0016_auto_20160820_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysiteprofile',
            old_name='Группа',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='mysiteprofile',
            old_name='Отчество',
            new_name='group',
        ),
    ]
