# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0019_request_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
